name: CI/CD Pipeline Production

on:
  push:
    brances:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
    # Deploy start
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/foodie-fiend
            git stash
            git pull origin main
            git status
            git stash pop
            exec bash
            composer update
