name: CI/CD Pipeline

on:
  push:
    brances:
      - development

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/foodie-fiend
            git stash
            git pull origin development
            git satus
            git stash pop
            exec bash
            composer update